# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.7
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# pylint: skip-file

from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_pyhidapi_win', [dirname(__file__)])
        except ImportError:
            import cochlear.protocols.drivers.pyhidapi._pyhidapi_win as _pyhidapi_win
            return _pyhidapi_win
        if fp is not None:
            try:
                _mod = imp.load_module('_pyhidapi_win', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _pyhidapi_win = swig_import_helper()
    del swig_import_helper
else:
    import cochlear.protocols.drivers.pyhidapi._pyhidapi_win as _pyhidapi_win
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError(name)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class hid_device_info(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, hid_device_info, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, hid_device_info, name)
    __repr__ = _swig_repr
    __swig_setmethods__["path"] = _pyhidapi_win.hid_device_info_path_set
    __swig_getmethods__["path"] = _pyhidapi_win.hid_device_info_path_get
    if _newclass:
        path = _swig_property(_pyhidapi_win.hid_device_info_path_get, _pyhidapi_win.hid_device_info_path_set)
    __swig_setmethods__["vendor_id"] = _pyhidapi_win.hid_device_info_vendor_id_set
    __swig_getmethods__["vendor_id"] = _pyhidapi_win.hid_device_info_vendor_id_get
    if _newclass:
        vendor_id = _swig_property(_pyhidapi_win.hid_device_info_vendor_id_get, _pyhidapi_win.hid_device_info_vendor_id_set)
    __swig_setmethods__["product_id"] = _pyhidapi_win.hid_device_info_product_id_set
    __swig_getmethods__["product_id"] = _pyhidapi_win.hid_device_info_product_id_get
    if _newclass:
        product_id = _swig_property(_pyhidapi_win.hid_device_info_product_id_get, _pyhidapi_win.hid_device_info_product_id_set)
    __swig_setmethods__["serial_number"] = _pyhidapi_win.hid_device_info_serial_number_set
    __swig_getmethods__["serial_number"] = _pyhidapi_win.hid_device_info_serial_number_get
    if _newclass:
        serial_number = _swig_property(_pyhidapi_win.hid_device_info_serial_number_get, _pyhidapi_win.hid_device_info_serial_number_set)
    __swig_setmethods__["release_number"] = _pyhidapi_win.hid_device_info_release_number_set
    __swig_getmethods__["release_number"] = _pyhidapi_win.hid_device_info_release_number_get
    if _newclass:
        release_number = _swig_property(_pyhidapi_win.hid_device_info_release_number_get, _pyhidapi_win.hid_device_info_release_number_set)
    __swig_setmethods__["manufacturer_string"] = _pyhidapi_win.hid_device_info_manufacturer_string_set
    __swig_getmethods__["manufacturer_string"] = _pyhidapi_win.hid_device_info_manufacturer_string_get
    if _newclass:
        manufacturer_string = _swig_property(_pyhidapi_win.hid_device_info_manufacturer_string_get, _pyhidapi_win.hid_device_info_manufacturer_string_set)
    __swig_setmethods__["product_string"] = _pyhidapi_win.hid_device_info_product_string_set
    __swig_getmethods__["product_string"] = _pyhidapi_win.hid_device_info_product_string_get
    if _newclass:
        product_string = _swig_property(_pyhidapi_win.hid_device_info_product_string_get, _pyhidapi_win.hid_device_info_product_string_set)
    __swig_setmethods__["usage_page"] = _pyhidapi_win.hid_device_info_usage_page_set
    __swig_getmethods__["usage_page"] = _pyhidapi_win.hid_device_info_usage_page_get
    if _newclass:
        usage_page = _swig_property(_pyhidapi_win.hid_device_info_usage_page_get, _pyhidapi_win.hid_device_info_usage_page_set)
    __swig_setmethods__["usage"] = _pyhidapi_win.hid_device_info_usage_set
    __swig_getmethods__["usage"] = _pyhidapi_win.hid_device_info_usage_get
    if _newclass:
        usage = _swig_property(_pyhidapi_win.hid_device_info_usage_get, _pyhidapi_win.hid_device_info_usage_set)
    __swig_setmethods__["interface_number"] = _pyhidapi_win.hid_device_info_interface_number_set
    __swig_getmethods__["interface_number"] = _pyhidapi_win.hid_device_info_interface_number_get
    if _newclass:
        interface_number = _swig_property(_pyhidapi_win.hid_device_info_interface_number_get, _pyhidapi_win.hid_device_info_interface_number_set)
    __swig_setmethods__["next"] = _pyhidapi_win.hid_device_info_next_set
    __swig_getmethods__["next"] = _pyhidapi_win.hid_device_info_next_get
    if _newclass:
        next = _swig_property(_pyhidapi_win.hid_device_info_next_get, _pyhidapi_win.hid_device_info_next_set)

    def __init__(self):
        this = _pyhidapi_win.new_hid_device_info()
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _pyhidapi_win.delete_hid_device_info
    __del__ = lambda self: None
hid_device_info_swigregister = _pyhidapi_win.hid_device_info_swigregister
hid_device_info_swigregister(hid_device_info)


class hid_wchar_string(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, hid_wchar_string, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, hid_wchar_string, name)
    __repr__ = _swig_repr
    __swig_setmethods__["wchar_string"] = _pyhidapi_win.hid_wchar_string_wchar_string_set
    __swig_getmethods__["wchar_string"] = _pyhidapi_win.hid_wchar_string_wchar_string_get
    if _newclass:
        wchar_string = _swig_property(_pyhidapi_win.hid_wchar_string_wchar_string_get, _pyhidapi_win.hid_wchar_string_wchar_string_set)

    def __init__(self):
        this = _pyhidapi_win.new_hid_wchar_string()
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _pyhidapi_win.delete_hid_wchar_string
    __del__ = lambda self: None
hid_wchar_string_swigregister = _pyhidapi_win.hid_wchar_string_swigregister
hid_wchar_string_swigregister(hid_wchar_string)


def hid_init():
    return _pyhidapi_win.hid_init()
hid_init = _pyhidapi_win.hid_init


def hid_exit():
    return _pyhidapi_win.hid_exit()
hid_exit = _pyhidapi_win.hid_exit


def hid_enumerate(*args):
    return _pyhidapi_win.hid_enumerate(*args)
hid_enumerate = _pyhidapi_win.hid_enumerate


def hid_free_enumeration(*args):
    return _pyhidapi_win.hid_free_enumeration(*args)
hid_free_enumeration = _pyhidapi_win.hid_free_enumeration


def hid_open(*args):
    return _pyhidapi_win.hid_open(*args)
hid_open = _pyhidapi_win.hid_open


def hid_open_path(*args):
    return _pyhidapi_win.hid_open_path(*args)
hid_open_path = _pyhidapi_win.hid_open_path


def hid_write(*args):
    return _pyhidapi_win.hid_write(*args)
hid_write = _pyhidapi_win.hid_write


def hid_read_timeout(*args):
    return _pyhidapi_win.hid_read_timeout(*args)
hid_read_timeout = _pyhidapi_win.hid_read_timeout


def hid_read(*args):
    return _pyhidapi_win.hid_read(*args)
hid_read = _pyhidapi_win.hid_read


def hid_set_nonblocking(*args):
    return _pyhidapi_win.hid_set_nonblocking(*args)
hid_set_nonblocking = _pyhidapi_win.hid_set_nonblocking


def hid_send_feature_report(*args):
    return _pyhidapi_win.hid_send_feature_report(*args)
hid_send_feature_report = _pyhidapi_win.hid_send_feature_report


def hid_get_feature_report(*args):
    return _pyhidapi_win.hid_get_feature_report(*args)
hid_get_feature_report = _pyhidapi_win.hid_get_feature_report


def hid_close(*args):
    return _pyhidapi_win.hid_close(*args)
hid_close = _pyhidapi_win.hid_close


def hid_get_manufacturer_string(*args):
    return _pyhidapi_win.hid_get_manufacturer_string(*args)
hid_get_manufacturer_string = _pyhidapi_win.hid_get_manufacturer_string


def hid_get_product_string(*args):
    return _pyhidapi_win.hid_get_product_string(*args)
hid_get_product_string = _pyhidapi_win.hid_get_product_string


def hid_get_serial_number_string(*args):
    return _pyhidapi_win.hid_get_serial_number_string(*args)
hid_get_serial_number_string = _pyhidapi_win.hid_get_serial_number_string


def hid_get_indexed_string(*args):
    return _pyhidapi_win.hid_get_indexed_string(*args)
hid_get_indexed_string = _pyhidapi_win.hid_get_indexed_string


def hid_error(*args):
    return _pyhidapi_win.hid_error(*args)
hid_error = _pyhidapi_win.hid_error


def hid_open_char(*args):
    return _pyhidapi_win.hid_open_char(*args)
hid_open_char = _pyhidapi_win.hid_open_char


def hid_get_product_string_buffer(*args):
    return _pyhidapi_win.hid_get_product_string_buffer(*args)
hid_get_product_string_buffer = _pyhidapi_win.hid_get_product_string_buffer


def hid_get_serial_number_string_buffer(*args):
    return _pyhidapi_win.hid_get_serial_number_string_buffer(*args)
hid_get_serial_number_string_buffer = _pyhidapi_win.hid_get_serial_number_string_buffer


def hid_get_manufacturer_string_buffer(*args):
    return _pyhidapi_win.hid_get_manufacturer_string_buffer(*args)
hid_get_manufacturer_string_buffer = _pyhidapi_win.hid_get_manufacturer_string_buffer
# This file is compatible with both classic and new-style classes.
