/*jslint nomen: true, regexp: true, unparam: true, sloppy: true, white: true */
/*global window, console, document, $, jQuery, PIE */

window.magichat = {};
window.magichat.set_callback = function (name, func) {
};
window.CR220_DATA = [
	{
		'identifier': 1,
		'selected': false,
		'local_date': 'July 18th - 8:49am',
		'dob': '1975-05-20',
		'implant_serial': '',
		'implant_serial_options': ['9284653729', '4215234123512'],
		'locus': '',
		'locus_options': ['Left', 'Right'],
		'name_first': 'Joseph',
		'name_last': 'Brendans',
		'name_full': 'Joseph Brendans',
		'gender': 'Male',
		'gender_options': ['Male', 'Female'],
		'surgery': 'Sydney Surgery',
		'surgery_options': ['Sydney Surgery', 'Kings Day Surgery'],
		'surgeon': 'Sam Reynold',
		'surgeon_options': ['Sam Reynold', 'Linus van Pelt', 'Snoopy', 'Schroeder'],
		'clinic': 'Hills Clinic',
		'clinic_options': ['Hills Clinic', 'House MD Clinic']
	},
	{
		'identifier': 2,
		'selected': false,
		'local_date': 'July 18th - 8:49am',
		'dob': '1975-05-20',
		'implant_serial': '',
		'implant_serial_options': ['9284653729', '4215234123512'],
		'locus': '',
		'locus_options': ['Left', 'Right'],
		'name_first': 'Joseph',
		'name_last': 'Brendans',
		'name_full': 'Joseph Brendans',
		'gender': 'Male',
		'gender_options': ['Male', 'Female'],
		'surgery': 'Sydney Surgery',
		'surgery_options': ['Sydney Surgery', 'Kings Day Surgery'],
		'surgeon': 'Sam Reynold',
		'surgeon_options': ['Sam Reynold', 'Linus van Pelt', 'Snoopy', 'Schroeder'],
		'clinic': 'Hills Clinic',
		'clinic_options': ['Hills Clinic', 'House MD Clinic']
	},
	{
		'identifier': 3,
		'selected': false,
		'local_date': 'July 18th - 8:49am',
		'dob': '1975-05-20',
		'implant_serial': '',
		'implant_serial_options': ['9284653729', '4215234123512'],
		'locus': '',
		'locus_options': ['Left', 'Right'],
		'name_first': 'Joseph',
		'name_last': 'Brendans',
		'name_full': 'Joseph Brendans',
		'gender': 'Male',
		'gender_options': ['Male', 'Female'],
		'surgery': 'Sydney Surgery',
		'surgery_options': ['Sydney Surgery', 'Kings Day Surgery'],
		'surgeon': 'Sam Reynold',
		'surgeon_options': ['Sam Reynold', 'Linus van Pelt', 'Snoopy', 'Schroeder'],
		'clinic': 'Hills Clinic',
		'clinic_options': ['Hills Clinic', 'House MD Clinic']
	},
	{
		'identifier': 4,
		'selected': false,
		'local_date': 'July 18th - 8:49am',
		'dob': '1975-05-20',
		'implant_serial': '',
		'implant_serial_options': ['9284653729', '4215234123512'],
		'locus': '',
		'locus_options': ['Left', 'Right'],
		'name_first': 'Joseph',
		'name_last': 'Brendans',
		'name_full': 'Joseph Brendans',
		'gender': 'Male',
		'gender_options': ['Male', 'Female'],
		'surgery': 'Sydney Surgery',
		'surgery_options': ['Sydney Surgery', 'Kings Day Surgery'],
		'surgeon': 'Sam Reynold',
		'surgeon_options': ['Sam Reynold', 'Linus van Pelt', 'Snoopy', 'Schroeder'],
		'clinic': 'Hills Clinic',
		'clinic_options': ['Hills Clinic', 'House MD Clinic']
	},
	{
		'identifier': 5,
		'selected': false,
		'local_date': 'July 18th - 8:49am',
		'dob': '1975-05-20',
		'implant_serial': '',
		'implant_serial_options': ['9284653729', '4215234123512'],
		'locus': '',
		'locus_options': ['Left', 'Right'],
		'name_first': 'Joseph',
		'name_last': 'Brendans',
		'name_full': 'Joseph Brendans',
		'gender': 'Male',
		'gender_options': ['Male', 'Female'],
		'surgery': 'Sydney Surgery',
		'surgery_options': ['Sydney Surgery', 'Kings Day Surgery'],
		'surgeon': 'Sam Reynold',
		'surgeon_options': ['Sam Reynold', 'Linus van Pelt', 'Snoopy', 'Schroeder'],
		'clinic': 'Hills Clinic',
		'clinic_options': ['Hills Clinic', 'House MD Clinic']
	},
	{
		'identifier': 6,
		'selected': false,
		'local_date': 'July 18th - 8:49am',
		'dob': '1975-05-20',
		'implant_serial': '',
		'implant_serial_options': ['9284653729', '4215234123512'],
		'locus': '',
		'locus_options': ['Left', 'Right'],
		'name_first': 'Joseph',
		'name_last': 'Brendans',
		'name_full': 'Joseph Brendans',
		'gender': 'Male',
		'gender_options': ['Male', 'Female'],
		'surgery': 'Sydney Surgery',
		'surgery_options': ['Sydney Surgery', 'Kings Day Surgery'],
		'surgeon': 'Sam Reynold',
		'surgeon_options': ['Sam Reynold', 'Linus van Pelt', 'Snoopy', 'Schroeder'],
		'clinic': 'Hills Clinic',
		'clinic_options': ['Hills Clinic', 'House MD Clinic']
	},
	{
		'identifier': 7,
		'selected': false,
		'local_date': 'July 18th - 8:49am',
		'dob': '1975-05-20',
		'implant_serial': '',
		'implant_serial_options': ['9284653729', '4215234123512'],
		'locus': '',
		'locus_options': ['Left', 'Right'],
		'name_first': 'Joseph',
		'name_last': 'Brendans',
		'name_full': 'Joseph Brendans',
		'gender': 'Male',
		'gender_options': ['Male', 'Female'],
		'surgery': 'Sydney Surgery',
		'surgery_options': ['Sydney Surgery', 'Kings Day Surgery'],
		'surgeon': 'Sam Reynold',
		'surgeon_options': ['Sam Reynold', 'Linus van Pelt', 'Snoopy', 'Schroeder'],
		'clinic': 'Hills Clinic',
		'clinic_options': ['Hills Clinic', 'House MD Clinic']
	},
	{
		'identifier': 8,
		'selected': false,
		'local_date': 'July 18th - 8:49am',
		'dob': '1975-05-20',
		'implant_serial': '',
		'implant_serial_options': ['9284653729', '4215234123512'],
		'locus': '',
		'locus_options': ['Left', 'Right'],
		'name_first': 'Joseph',
		'name_last': 'Brendans',
		'name_full': 'Joseph Brendans',
		'gender': 'Male',
		'gender_options': ['Male', 'Female'],
		'surgery': 'Sydney Surgery',
		'surgery_options': ['Sydney Surgery', 'Kings Day Surgery'],
		'surgeon': 'Sam Reynold',
		'surgeon_options': ['Sam Reynold', 'Linus van Pelt', 'Snoopy', 'Schroeder'],
		'clinic': 'Hills Clinic',
		'clinic_options': ['Hills Clinic', 'House MD Clinic']
	},
	{
		'identifier': 9,
		'selected': false,
		'local_date': 'July 18th - 8:49am',
		'dob': '1975-05-20',
		'implant_serial': '',
		'implant_serial_options': ['9284653729', '4215234123512'],
		'locus': '',
		'locus_options': ['Left', 'Right'],
		'name_first': 'Joseph',
		'name_last': 'Brendans',
		'name_full': 'Joseph Brendans',
		'gender': 'Male',
		'gender_options': ['Male', 'Female'],
		'surgery': 'Sydney Surgery',
		'surgery_options': ['Sydney Surgery', 'Kings Day Surgery'],
		'surgeon': 'Sam Reynold',
		'surgeon_options': ['Sam Reynold', 'Linus van Pelt', 'Snoopy', 'Schroeder'],
		'clinic': 'Hills Clinic',
		'clinic_options': ['Hills Clinic', 'House MD Clinic']
	},
	{
		'identifier': 10,
		'selected': false,
		'local_date': 'July 18th - 8:49am',
		'dob': '1975-05-20',
		'implant_serial': '',
		'implant_serial_options': ['9284653729', '4215234123512'],
		'locus': '',
		'locus_options': ['Left', 'Right'],
		'name_first': 'Joseph',
		'name_last': 'Brendans',
		'name_full': 'Joseph Brendans',
		'gender': 'Male',
		'gender_options': ['Male', 'Female'],
		'surgery': 'Sydney Surgery',
		'surgery_options': ['Sydney Surgery', 'Kings Day Surgery'],
		'surgeon': 'Sam Reynold',
		'surgeon_options': ['Sam Reynold', 'Linus van Pelt', 'Snoopy', 'Schroeder'],
		'clinic': 'Hills Clinic',
		'clinic_options': ['Hills Clinic', 'House MD Clinic']
	},
	{
		'identifier': 11,
		'selected': false,
		'local_date': 'July 18th - 8:49am',
		'dob': '1975-05-20',
		'implant_serial': '',
		'implant_serial_options': ['9284653729', '4215234123512'],
		'locus': '',
		'locus_options': ['Left', 'Right'],
		'name_first': 'Joseph',
		'name_last': 'Brendans',
		'name_full': 'Joseph Brendans',
		'gender': 'Male',
		'gender_options': ['Male', 'Female'],
		'surgery': 'Sydney Surgery',
		'surgery_options': ['Sydney Surgery', 'Kings Day Surgery'],
		'surgeon': 'Sam Reynold',
		'surgeon_options': ['Sam Reynold', 'Linus van Pelt', 'Snoopy', 'Schroeder'],
		'clinic': 'Hills Clinic',
		'clinic_options': ['Hills Clinic', 'House MD Clinic']
	},
	{
		'identifier': 12,
		'selected': false,
		'local_date': 'July 18th - 8:49am',
		'dob': '1975-05-20',
		'implant_serial': '',
		'implant_serial_options': ['9284653729', '4215234123512'],
		'locus': '',
		'locus_options': ['Left', 'Right'],
		'name_first': 'Joseph',
		'name_last': 'Brendans',
		'name_full': 'Joseph Brendans',
		'gender': 'Male',
		'gender_options': ['Male', 'Female'],
		'surgery': 'Sydney Surgery',
		'surgery_options': ['Sydney Surgery', 'Kings Day Surgery'],
		'surgeon': 'Sam Reynold',
		'surgeon_options': ['Sam Reynold', 'Linus van Pelt', 'Snoopy', 'Schroeder'],
		'clinic': 'Hills Clinic',
		'clinic_options': ['Hills Clinic', 'House MD Clinic']
	},
	{
		'identifier': 13,
		'selected': false,
		'local_date': 'July 18th - 8:49am',
		'dob': '1975-05-20',
		'implant_serial': '',
		'implant_serial_options': ['9284653729', '4215234123512'],
		'locus': '',
		'locus_options': ['Left', 'Right'],
		'name_first': 'Joseph',
		'name_last': 'Brendans',
		'name_full': 'Joseph Brendans',
		'gender': 'Male',
		'gender_options': ['Male', 'Female'],
		'surgery': 'Sydney Surgery',
		'surgery_options': ['Sydney Surgery', 'Kings Day Surgery'],
		'surgeon': 'Sam Reynold',
		'surgeon_options': ['Sam Reynold', 'Linus van Pelt', 'Snoopy', 'Schroeder'],
		'clinic': 'Hills Clinic',
		'clinic_options': ['Hills Clinic', 'House MD Clinic']
	},
	{
		'identifier': 14,
		'selected': false,
		'local_date': 'July 18th - 8:49am',
		'dob': '1975-05-20',
		'implant_serial': '',
		'implant_serial_options': ['9284653729', '4215234123512'],
		'locus': '',
		'locus_options': ['Left', 'Right'],
		'name_first': 'Joseph',
		'name_last': 'Brendans',
		'name_full': 'Joseph Brendans',
		'gender': 'Male',
		'gender_options': ['Male', 'Female'],
		'surgery': 'Sydney Surgery',
		'surgery_options': ['Sydney Surgery', 'Kings Day Surgery'],
		'surgeon': 'Sam Reynold',
		'surgeon_options': ['Sam Reynold', 'Linus van Pelt', 'Snoopy', 'Schroeder'],
		'clinic': 'Hills Clinic',
		'clinic_options': ['Hills Clinic', 'House MD Clinic']
	},
	{
		'identifier': 15,
		'selected': false,
		'local_date': 'July 18th - 8:49am',
		'dob': '1975-05-20',
		'implant_serial': '',
		'implant_serial_options': ['9284653729', '4215234123512'],
		'locus': '',
		'locus_options': ['Left', 'Right'],
		'name_first': 'Joseph',
		'name_last': 'Brendans',
		'name_full': 'Joseph Brendans',
		'gender': 'Male',
		'gender_options': ['Male', 'Female'],
		'surgery': 'Sydney Surgery',
		'surgery_options': ['Sydney Surgery', 'Kings Day Surgery'],
		'surgeon': 'Sam Reynold',
		'surgeon_options': ['Sam Reynold', 'Linus van Pelt', 'Snoopy', 'Schroeder'],
		'clinic': 'Hills Clinic',
		'clinic_options': ['Hills Clinic', 'House MD Clinic']
	},
	{
		'identifier': 16,
		'selected': false,
		'local_date': 'July 18th - 8:49am',
		'dob': '1975-05-20',
		'implant_serial': '',
		'implant_serial_options': ['9284653729', '4215234123512'],
		'locus': '',
		'locus_options': ['Left', 'Right'],
		'name_first': 'Joseph',
		'name_last': 'Brendans',
		'name_full': 'Joseph Brendans',
		'gender': 'Male',
		'gender_options': ['Male', 'Female'],
		'surgery': 'Sydney Surgery',
		'surgery_options': ['Sydney Surgery', 'Kings Day Surgery'],
		'surgeon': 'Sam Reynold',
		'surgeon_options': ['Sam Reynold', 'Linus van Pelt', 'Snoopy', 'Schroeder'],
		'clinic': 'Hills Clinic',
		'clinic_options': ['Hills Clinic', 'House MD Clinic']
	},
	{
		'identifier': 17,
		'selected': false,
		'local_date': 'July 18th - 8:49am',
		'dob': '1975-05-20',
		'implant_serial': '',
		'implant_serial_options': ['9284653729', '4215234123512'],
		'locus': '',
		'locus_options': ['Left', 'Right'],
		'name_first': 'Joseph',
		'name_last': 'Brendans',
		'name_full': 'Joseph Brendans',
		'gender': 'Male',
		'gender_options': ['Male', 'Female'],
		'surgery': 'Sydney Surgery',
		'surgery_options': ['Sydney Surgery', 'Kings Day Surgery'],
		'surgeon': 'Sam Reynold',
		'surgeon_options': ['Sam Reynold', 'Linus van Pelt', 'Snoopy', 'Schroeder'],
		'clinic': 'Hills Clinic',
		'clinic_options': ['Hills Clinic', 'House MD Clinic']
	},
	{
		'identifier': 18,
		'selected': false,
		'local_date': 'July 18th - 8:49am',
		'dob': '1975-05-20',
		'implant_serial': '',
		'implant_serial_options': ['9284653729', '4215234123512'],
		'locus': '',
		'locus_options': ['Left', 'Right'],
		'name_first': 'Joseph',
		'name_last': 'Brendans',
		'name_full': 'Joseph Brendans',
		'gender': 'Male',
		'gender_options': ['Male', 'Female'],
		'surgery': 'Sydney Surgery',
		'surgery_options': ['Sydney Surgery', 'Kings Day Surgery'],
		'surgeon': 'Sam Reynold',
		'surgeon_options': ['Sam Reynold', 'Linus van Pelt', 'Snoopy', 'Schroeder'],
		'clinic': 'Hills Clinic',
		'clinic_options': ['Hills Clinic', 'House MD Clinic']
	},
	{
		'identifier': 19,
		'selected': false,
		'local_date': 'July 18th - 8:49am',
		'dob': '1975-05-20',
		'implant_serial': '',
		'implant_serial_options': ['9284653729', '4215234123512'],
		'locus': '',
		'locus_options': ['Left', 'Right'],
		'name_first': 'Joseph',
		'name_last': 'Brendans',
		'name_full': 'Joseph Brendans',
		'gender': 'Male',
		'gender_options': ['Male', 'Female'],
		'surgery': 'Sydney Surgery',
		'surgery_options': ['Sydney Surgery', 'Kings Day Surgery'],
		'surgeon': 'Sam Reynold',
		'surgeon_options': ['Sam Reynold', 'Linus van Pelt', 'Snoopy', 'Schroeder'],
		'clinic': 'Hills Clinic',
		'clinic_options': ['Hills Clinic', 'House MD Clinic']
	},
	{
		'identifier': 20,
		'selected': false,
		'local_date': 'July 18th - 8:49am',
		'dob': '1975-05-20',
		'implant_serial': '',
		'implant_serial_options': ['9284653729', '4215234123512'],
		'locus': '',
		'locus_options': ['Left', 'Right'],
		'name_first': 'Joseph',
		'name_last': 'Brendans',
		'name_full': 'Joseph Brendans',
		'gender': 'Male',
		'gender_options': ['Male', 'Female'],
		'surgery': 'Sydney Surgery',
		'surgery_options': ['Sydney Surgery', 'Kings Day Surgery'],
		'surgeon': 'Sam Reynold',
		'surgeon_options': ['Sam Reynold', 'Linus van Pelt', 'Snoopy', 'Schroeder'],
		'clinic': 'Hills Clinic',
		'clinic_options': ['Hills Clinic', 'House MD Clinic']
	}
];
window.CRF_DATA = [
	{
		'identifier': 100,
		'selected': false,
		'local_date': 'July 18th - 8:49am',
		'dob': '1947-06-22',
		'locus': 'Left',
		'name_first': 'Joseph',
		'name_last': 'Brendans',
		'name_full': 'Joseph Brendans',
		'gender': 'Male',
		'surgery': "Li'l Folks Surgery",
		'surgeon': 'Lucy van Pelt'
	},
	{
		'identifier': 101,
		'selected': false,
		'local_date': 'July 18th - 8:49am',
		'dob': '1947-06-22',
		'locus': 'Left',
		'name_first': 'Joseph',
		'name_last': 'Brendans',
		'name_full': 'Joseph Brendans',
		'gender': 'Male',
		'surgery': "Li'l Folks Surgery",
		'surgeon': 'Lucy van Pelt'
	},
	{
		'identifier': 102,
		'selected': false,
		'local_date': 'July 18th - 8:49am',
		'dob': '1947-06-22',
		'locus': 'Left',
		'name_first': 'Joseph',
		'name_last': 'Brendans',
		'name_full': 'Joseph Brendans',
		'gender': 'Male',
		'surgery': "Li'l Folks Surgery",
		'surgeon': 'Lucy van Pelt'
	}
];
window.HISTORY_DATA = [
	{
		'identifier': 200,
		'selected': false,
		'name_first': 'Joseph',
		'name_last': 'Brendans',
		'name_full': 'Joseph Brendans',
		'surgery': "Li'l Folks Surgery",
		'surgeon': 'Lucy van Pelt',
		'clinic': 'Hills Clinic',
		'status': 'Sending'
	},
	{
		'identifier': 201,
		'selected': false,
		'name_first': 'Joseph',
		'name_last': 'Brendans',
		'name_full': 'Joseph Brendans',
		'surgery': "Li'l Folks Surgery",
		'surgeon': 'Lucy van Pelt',
		'clinic': 'Hills Clinic',
		'status': 'Exported Successfully'
	},
	{
		'identifier': 202,
		'selected': false,
		'name_first': 'Joseph',
		'name_last': 'Brendans',
		'name_full': 'Joseph Brendans',
		'surgery': "Li'l Folks Surgery",
		'surgeon': 'Lucy van Pelt',
		'clinic': 'Hills Clinic',
		'status': 'Sent Successfully'
	}
];

window.magichat.CAN_NEW = ['surgery_options', 'clinic_options', 'surgeon_options'];
window.magichat.event_onload = function () {
	set_view('cr220_view', window.magichat.CAN_NEW, 'template_header_cr220', 'template_row_cr220', window.CR220_DATA);
	set_view('crf_view', window.magichat.CAN_NEW, 'template_header_crf', 'template_row_crf', window.CRF_DATA);
	set_view('history_view', window.magichat.CAN_NEW, 'template_header_history', 'template_row_history', window.HISTORY_DATA);
};
window.magichat.poll = function () {
};

window.magichat.on_row_value_changed = function () {
	log.info('On row value changed: Event ignored in html mode');
};

window.magichat.on_modal_shown = function () {
};

window.magichat.on_modal_hide = function () {
};

window.magichat.on_click_view = function (identifier) {
	var data = window.CR220_DATA[0];
	log.info('Stubbornly displaying the first row only in html mode');
	show_modal('view', window.magichat.CAN_NEW, identifier, data)
};

window.magichat.on_click_new = function (identifier, key) {
	log.info(identifier, key);
	if (key == 'clinic') {
		data = {'clinic': '', 'cochlear_id': '', 'address': ''}
	} else if (key == 'surgery') {
		data = {'surgery': '', 'cochlear_id': '', 'address': ''}
	} else if (key == 'surgeon') {
		data = {'surgeon': '', 'cochlear_id': '', 'address': ''}
	} else {
		data = {}
	}
	hide_current_modal();
	show_modal(key, identifier, data);
};